select 'drop '||object_type||' '|| object_name|| DECODE(OBJECT_TYPE,'TABLE',' CASCADE CONSTRAINTS','') || ';'  from user_objects WHERE object_name LIKE '%QLNV_KHVONPHI%';

	CREATE TABLE "QLNV_KHVONPHI" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"MA_BCAO" VARCHAR2(20 BYTE),
		"NAM_BCAO" NUMBER,
		"NAM_HIEN_HANH" NUMBER,
		"TRANG_THAI" VARCHAR2(20 BYTE),
		"MA_LOAI_BCAO" VARCHAR2(20 BYTE),
		"NGAY_TAO" TIMESTAMP (6),
		"NGUOI_TAO" VARCHAR2(20 BYTE),
		"NGAY_SUA" TIMESTAMP (6),
		"NGUOI_SUA" VARCHAR2(20 BYTE),
		"MA_DVI_TIEN" VARCHAR2(20 BYTE),
		"MA_DVI"NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_PK" PRIMARY KEY ("ID"));

---1
	CREATE TABLE "QLNV_KHVONPHI_DM_VONDT_XDCBGD3N" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"STT" NUMBER,
		"TEN_DAN" VARCHAR2(20 BYTE),
		"MA_KHOACH" VARCHAR2(20 BYTE),
		"MA_KHOI_DAN" VARCHAR2(20 BYTE),
		"MA_DDIEM_XD" VARCHAR2(20 BYTE),
		"DDIEM_MO_TAIKHOAN" VARCHAR2(20 BYTE),
		"MASO_DAN" VARCHAR2(20 BYTE),
		"MA_NGANH_KTE" VARCHAR2(20 BYTE),
		"NLUC_TKE" VARCHAR2(20 BYTE),
		"NAM_KC_TTE" NUMBER,
		"NAM_HT_TTE" NUMBER,
		"QD_DUYET_DAN_DTU_SONGAYTHANG" VARCHAR2(20 BYTE),
		"QD_DUYET_DAN_DTU_TONG_VON" NUMBER,

		"QD_DCHINH_DAN_DTU_SONGAYTHANG" VARCHAR2(20 BYTE),
		"QD_DCHINH_DAN_DTU_TONG_VON" NUMBER,

		"QD_DUYET_TK_DTOAN_SONGAYTHANG" VARCHAR2(20 BYTE),
		"QD_DUYET_TK_DTOAN_TONG" NUMBER,
		"QD_DUYET_TK_DTOAN_XL" NUMBER,
		"QD_DUYET_TK_DTOAN_TB" NUMBER,
		"QD_DUYET_TK_DTOAN_CX" NUMBER,

		"KLTH_CAP_DEN_3006_SONGAYTHANG" VARCHAR2(20 BYTE),
		"KLTH_CAP_DEN_3006_NSTT" NUMBER,
		"KLTH_CAP_DEN_3006_DTOAN_CHI_TX" NUMBER,
		"KLTH_CAP_DEN_3006_QUYKHAC" NUMBER,

		"KLTH_CAP_DEN_3112_SONGAYTHANG" VARCHAR2(20 BYTE),
		"KLTH_CAP_DEN_3112_NSTT" NUMBER,
		"KLTH_CAP_DEN_3112_DTOAN_CHI_TX" NUMBER,
		"KLTH_CAP_DEN_3112_QUYKHAC" NUMBER,
		"NCAU_VON_N1" NUMBER,
		"NCAU_VON_N2" NUMBER,
		"NCAU_VON_N3" NUMBER,
		"GHICHU" VARCHAR2(20 BYTE),
		CONSTRAINT "QLNV_KHVONPHI_DM_VONDT_XDCBGD3N_PK" PRIMARY KEY ("ID"));
 ---alter TABLE "QLNV_KHVONPHI_DM_VONDT_XDCBGD3N" ADD 

---2

 	CREATE TABLE "QLNV_KHVONPHI_NXUAT_DTQG_HNAM_THOC_GAO" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"LUONG_THOC_XUAT" NUMBER,
		"LUONG_THOC_NHAP" NUMBER,
		"LUONG_GAO_XUAT" NUMBER,
		"LUONG_GAO_NHAP" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_NXUAT_DTQG_HNAM_THOC_GAO_PK" PRIMARY KEY ("ID"));


CREATE TABLE "QLNV_KHVONPHI_NXUAT_DTQG_HNAM_VATTU" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"STT" NUMBER,
		"MA_TBI" VARCHAR2(20 BYTE),
		"SL_NHAP" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_NXUAT_DTQG_HNAM_VATTU_PK" PRIMARY KEY ("ID"));

---3
CREATE TABLE "QLNV_KHVONPHI_KHOACH_BQUAN_HNAM_THOC_GAO" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"KPHI_BQUAN_THOC_TX" NUMBER,
		"KPHI_BQUAN_THOC_LD" NUMBER,
		"KPHI_BQUAN_GAO_TX" NUMBER,
		"KPHI_BQUAN_GAO_LD" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_KHOACH_BQUAN_HNAM_THOC_GAO_PK" PRIMARY KEY ("ID"));


 CREATE TABLE "QLNV_KHVONPHI_KHOACH_BQUAN_HNAM_MAT_HANG" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"STT" NUMBER,
		"MA_MAT_HANG" VARCHAR2(20 BYTE),
		"MA_NHOM" VARCHAR2(20 BYTE),
		"KPHI" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_KHOACH_BQUAN_HNAM_MAT_HANG_PK" PRIMARY KEY ("ID"));


 ---4

	CREATE TABLE "QLNV_KHVONPHI_NCAU_XUAT_DTQG_VTRO_HNAM" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"LUONG_XUAT_VTRO" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_NCAU_XUAT_DTQG_VTRO_HNAM_PK" PRIMARY KEY ("ID"));


---5

	CREATE TABLE "QLNV_KHVONPHI_KHOACH_QUY_TIEN_LUONG_GD3N" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"STT" NUMBER,
		"MA_DVI" VARCHAR2(20 BYTE),

		"TONG_CBO_N" VARCHAR2(20 BYTE),
		"TONG_BCHE_DUOC_PD_N" VARCHAR2(20 BYTE),
		"TONG_QUY_LUONG_CO_TCHAT_LUONG_N" VARCHAR2(20 BYTE),
		"TONG_QUY_LUONG_CO_TCHAT_LUONG_THEO_BCHE_N" VARCHAR2(20 BYTE),
		"LUONG_CBAN_N" VARCHAR2(20 BYTE),
		"PHU_CAP_N" VARCHAR2(20 BYTE),
		"CAC_KHOAN_DGOP_N" VARCHAR2(20 BYTE),

		"TONG_CBO_THIEN_N" NUMBER,
		"TONG_BCHE_DUOC_PD_THIEN_N" NUMBER,
		"TONG_QUY_LUONG_CO_TCHAT_LUONG_THIEN_N" NUMBER,
		"TONG_QUY_LUONG_CO_TCHAT_LUONG_THEO_BCHE_THIEN_N" NUMBER,
		"LUONG_CBAN_THIEN_N" NUMBER,
		"PHU_CAP_THIEN_N" NUMBER,
		"CAC_KHOAN_DGOP_THIEN_N" NUMBER,

		"TONG_CBO_N1" NUMBER,
		"TONG_BCHE_DUOC_PD_N1" NUMBER,
		"TONG_QUY_LUONG_CO_TCHAT_LUONG_N1" NUMBER,
		"TONG_QUY_LUONG_CO_TCHAT_LUONG_THEO_BCHE_N1" NUMBER,
		"LUONG_CBAN_N1" NUMBER,
		"PHU_CAP_N1" NUMBER,
		"CAC_KHOAN_DGOP_N1" NUMBER,

		"TONG_CBO_N2" NUMBER,
		"TONG_BCHE_DUOC_PD_N2" NUMBER,
		"TONG_QUY_LUONG_CO_TCHAT_LUONG_N2" NUMBER,
		"TONG_QUY_LUONG_CO_TCHAT_LUONG_THEO_BCHE_N2" NUMBER,
		"LUONG_CBAN_N2" NUMBER,
		"PHU_CAP_N2" NUMBER,
		"CAC_KHOAN_DGOP_N2" NUMBER,

		"TONG_CBO_N3" NUMBER,
		"TONG_BCHE_DUOC_PD_N3" NUMBER,
		"TONG_QUY_LUONG_CO_TCHAT_LUONG_N3" NUMBER,
		"TONG_QUY_LUONG_CO_TCHAT_LUONG_THEO_BCHE_N3" NUMBER,
		"LUONG_CBAN_N3" NUMBER,
		"PHU_CAP_N3" NUMBER,
		"CAC_KHOAN_DGOP_N3" NUMBER,

		CONSTRAINT "QLNV_KHVONPHI_KHOACH_QUY_TIEN_LUONG_GD3N_PK" PRIMARY KEY ("ID"));


---6
	CREATE TABLE "QLNV_KHVONPHI_KHOACH_QUY_TIEN_LUONG_HNAM" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"STT" NUMBER,
		"MA_DVI" VARCHAR2(20 BYTE),
		"BCHE_GIAO_N1" NUMBER,
		"DU_KIEN_SO_CCVC_CO_MAT_N1" NUMBER,
		"DU_KIEN_SO_HDONG_CO_MAT_N1" NUMBER,
		"BCHE_CHUA_SDUNG" NUMBER,
		"TONGQUY_LUONG_PCAP_THEO_LUONG_CCVC_HDLD" NUMBER,
		"TONG_SO" NUMBER,
		"CCVC_DU_KIEN_CO_MAT_N1_CONG" NUMBER,
		"CCVC_DU_KIEN_CO_MAT_N1_LUONG_THEO_BAC" NUMBER,
		"CCVC_DU_KIEN_CO_MAT_N1_PCAP" NUMBER,
		"CCVC_DU_KIEN_CO_MAT_N1_CKDG" NUMBER,
		"QUY_LUONG_TANG_NANG_BAC_LUONG_N1" NUMBER,
		"BCHE_CHUA_SDUNG_CONG" NUMBER,
		"BCHE_CHUA_SDUNG_LUONG" NUMBER,
		"BCHE_CHUA_SDUNG_CKDG" NUMBER,
		"QUY_LUONG_PCAP_THEO_HDLD" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_KHOACH_QUY_TIEN_LUONG_HNAM_PK" PRIMARY KEY ("ID"));


---7
	CREATE TABLE "QLNV_KHVONPHI_CHI_DTAI_DAN_NCKH_GD3N" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"STT" NUMBER,
		"TEN_DTAI_DAN" VARCHAR2(20 BYTE),
		"MA_DVI" VARCHAR2(20 BYTE),
		"TG_BDAU" NUMBER,
		"TG_KTHUC" NUMBER,
		"KPHI_TONG_PHI_DUOC_DUYET" NUMBER,
		"KPHI_DA_DUOC_BTRI" NUMBER,
		"KPHI_DUOC_THIEN_DEN_THOI_DIEM_BCAO" NUMBER,
		"KPHI_DU_KIEN_BTRI_N1" NUMBER,
		"KPHI_DU_KIEN_BTRI_N2" NUMBER,
		"KPHI_DU_KIEN_BTRI_N3" NUMBER,
		"KPHI_THUHOI" NUMBER,
		"KPHI_TGIAN_THUHOI" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_CHI_DTAI_DAN_NCKH_GD3N_PK" PRIMARY KEY ("ID"));


---8
	CREATE TABLE "QLNV_KHVONPHI_VBAN_QPHAM_PLUAT_DTQG_GD3N" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"STT" NUMBER,
		"TEN_VBAN" VARCHAR2(20 BYTE),
		"LOAI_VBAN" VARCHAR2(20 BYTE),
		"TGIAN_DU_KIEN" VARCHAR2(20 BYTE),
		"MA_DVI_CHU_TRI" VARCHAR2(20 BYTE),
		"DVI_PHOI_HOP" VARCHAR2(20 BYTE),
		"DTOAN_KPHI" NUMBER,
		"CCU_LAP_DTOAN" VARCHAR2(20 BYTE),
		CONSTRAINT "QLNV_KHVONPHI_VBAN_QPHAM_PLUAT_DTQG_GD3N_PK" PRIMARY KEY ("ID"));


---9
	CREATE TABLE "QLNV_KHVONPHI_CHI_UDUNG_CNTT_GD3N" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"STT" NUMBER,
		"NDUNG" VARCHAR2(20 BYTE),
		"LOAI_KHOACH" VARCHAR2(20 BYTE),
		"LOAI_DAN" VARCHAR2(20 BYTE),
		"TONG_DTOAN_SL" NUMBER,
		"TONG_DTOAN_GTRI" NUMBER,
		"THIEN_NAM_TRUOC" NUMBER,

		"CB_DTU_N" NUMBER,
		"TH_DTU_N" NUMBER,

		"CB_DTU_N1" NUMBER,
		"TH_DTU_N1" NUMBER,

		"CB_DTU_N2" NUMBER,
		"TH_DTU_N2" NUMBER,

		"CB_DTU_N3" NUMBER,
		"TH_DTU_N3" NUMBER,

		"GHI_CHU" VARCHAR2(20 BYTE),
		CONSTRAINT "QLNV_KHVONPHI_CHI_UDUNG_CNTT_GD3N_PK" PRIMARY KEY ("ID"));


---10
	CREATE TABLE "QLNV_KHVONPHI_DTOAN_CHI_MUASAM_MAYMOC_TBI_GD3N" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"STT" NUMBER,
		"MA_TBI" VARCHAR2(20 BYTE),
		"N1" NUMBER,
		"N2" NUMBER,
		"N3" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_DTOAN_CHI_MUASAM_MAYMOC_TBI_GD3N_PK" PRIMARY KEY ("ID"));

---11
	CREATE TABLE "QLNV_KHVONPHI_NCAU_CHI_NSNN_GD3N" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"STT" NUMBER,
		"MA_NDUNG" VARCHAR2(20 BYTE),
		"TEN_DAN" VARCHAR2(20 BYTE),
		"MA_LOAI_CHI" VARCHAR2(20 BYTE),
		"MA_KHOAN_CHI" VARCHAR2(20 BYTE),
		"MA_MUC_CHI" VARCHAR2(20 BYTE),
		"MA_LOAI_CHI_TX" VARCHAR2(20 BYTE),

		"DTOAN_N" NUMBER,
		"UOC_THIEN_N" NUMBER,

		"TRAN_CHI_N1" NUMBER,
		"NCAU_CHI_N1" NUMBER,
		"CLECH_TRAN_CHI_VS_NCAU_CHI_N1" NUMBER,

		"SSANH_NCAU_N_VOI_N_1" NUMBER,

		"TRAN_CHI_N2" NUMBER,
		"NCAU_CHI_N2" NUMBER,
		"CLECH_TRAN_CHI_VS_NCAU_CHI_N2" NUMBER,

		"TRAN_CHI_N3" NUMBER,
		"NCAU_CHI_N3" NUMBER,
		"CLECH_TRAN_CHI_VS_NCAU_CHI_N3" NUMBER,

		CONSTRAINT "QLNV_KHVONPHI_NCAU_CHI_NSNN_GD3N_PK" PRIMARY KEY ("ID"));



---12
	CREATE TABLE "QLNV_KHVONPHI_CHI_TX_GD3N" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"STT" NUMBER,
		"MA_NOI_DUNG" VARCHAR2(20 BYTE),
		"MA_NHOM_CHI" VARCHAR2(20 BYTE),
		"MA_LOAI_CHI" VARCHAR2(20 BYTE),

		"NAM_HHANH_N" NUMBER,
		"TRAN_CHI_DUOC_TB_N1" NUMBER,
		"NCAU_CHI_CUA_DVI_N1" NUMBER,
		"CLECH_TRAN_CHI_VS_NCAU_N1" NUMBER,

		"TRAN_CHI_DUOC_TB_N2" NUMBER,
		"NCAU_CHI_CUA_DVI_N2" NUMBER,
		"CLECH_TRAN_CHI_VS_NCAU_N2" NUMBER,

		"TRAN_CHI_DUOC_TB_N3" NUMBER,
		"NCAU_CHI_CUA_DVI_N3" NUMBER,
		"CLECH_TRAN_CHI_VS_NCAU_N3" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_CHI_TX_GD3N_PK" PRIMARY KEY ("ID"));


---13
	CREATE TABLE "QLNV_KHVONPHI_NCAU_PHI_NHAP_XUAT_GD3N" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"STT" NUMBER,
		"MA_VTU" VARCHAR2(20 BYTE),
		"MA_NHOM_CHI" VARCHAR2(20 BYTE),
		"MA_LOAI_CHI" VARCHAR2(20 BYTE),
		"MA_DVI_TINH" VARCHAR2(20 BYTE),
		"SL" NUMBER,
		"DMUC_PHI_TC" NUMBER,
		"THANH_TIEN" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_NCAU_PHI_NHAP_XUAT_GD3N_PK" PRIMARY KEY ("ID"));


---14
	CREATE TABLE "QLNV_KHVONPHI_KHOACH_CTAO_SCHUA_GD3N" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"STT" NUMBER,
		"TEN_CTRINH" VARCHAR2(20 BYTE),
		"MA_NGUON_VON" VARCHAR2(20 BYTE),
		"MA_LOAI_CT" VARCHAR2(20 BYTE),
		"TGIAN_KC" NUMBER,
		"TGIAN_HT" NUMBER,
		"MA_CQUAN_QD" VARCHAR2(20 BYTE),
		"TONG_GTRI" NUMBER,

		"DTOAN_KPHI_3006N" NUMBER,
		"UOC_THIEN_N" NUMBER,

		"DA_TTOAN_3006N" NUMBER,
		"UOC_TTOAN_N" NUMBER,

		"TSO_N1" NUMBER,
		"TTOAN_N1" NUMBER,
		"PHAT_SINH_N1" NUMBER,

		"TSO_N2" NUMBER,
		"TTOAN_N2" NUMBER,
		"PHAT_SINH_N2" NUMBER,

		"TSO_N3" NUMBER,
		"TTOAN_N3" NUMBER,
		"PHAT_SINH_N3" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_KHOACH_CTAO_SCHUA_GD3N_PK" PRIMARY KEY ("ID"));


---15
	CREATE TABLE "QLNV_KHVONPHI_KHOACH_DTAO_BOI_DUONG_GD3N" 
	(	"ID" NUMBER(19,0) NOT NULL ENABLE,
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE,
		"STT" NUMBER,
		"MA_LOAI" VARCHAR2(20 BYTE),
		"MA_KHOAN" VARCHAR2(20 BYTE),
		"MA_CHI_MUC" VARCHAR2(20 BYTE),
		"SO_LUOT_NGUOI_N1" NUMBER,
		"THANH_TIEN_N1" NUMBER,
		"SO_LUOT_NGUOI_N2" NUMBER,
		"THANH_TIEN_N2" NUMBER,
		"SO_LUOT_NGUOI_N3" NUMBER,
		"THANH_TIEN_N3" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_KHOACH_DTAO_BOI_DUONG_GD3N_PK" PRIMARY KEY ("ID"));


------ TC
---1
	CREATE TABLE "QLNV_KHVONPHI_TC_NCAU_KHOACH_DTXD_GD3N" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"TEN_DAN" VARCHAR2(20 BYTE),
		"MA_LOAI_KHOACH" VARCHAR2(20 BYTE),
		"MA_KHOI_DAN" VARCHAR2(20 BYTE),
		"MA_DDIEM_XDUNG" VARCHAR2(20 BYTE),
		"DDIEM_MO_TK" VARCHAR2(20 BYTE),
		"MA_NGANH_KTE" VARCHAR2(20 BYTE),
		"NLUC_TKE" VARCHAR2(20 BYTE),
		"NAM_KC_TTE" NUMBER,
		"NAM_HT_TTE" NUMBER,

		"QD_DUYET_DAN_DTU_SONGAYTHANG" VARCHAR2(20 BYTE),
		"QD_DUYET_DAN_DTU_TONG_VON" NUMBER,

		"QD_DCHINH_DAN_DTU_SONGAYTHANG" VARCHAR2(20 BYTE),
		"QD_DCHINH_DAN_DTU_TONG_VON" NUMBER,

		"QD_DUYET_TK_DTOAN_SONGAYTHANG" VARCHAR2(20 BYTE),
		"QD_DUYET_TK_DTOAN_TONG" NUMBER,
		"QD_DUYET_TK_DTOAN_XL" NUMBER,
		"QD_DUYET_TK_DTOAN_TB" NUMBER,
		"QD_DUYET_TK_DTOAN_CX" NUMBER,

		"KLTH_CAP_DEN_3006_SONGAYTHANG" VARCHAR2(20 BYTE),
		"KLTH_CAP_DEN_3006_NSTT" NUMBER,
		"KLTH_CAP_DEN_3006_DTOAN_CHI_TX" NUMBER,
		"KLTH_CAP_DEN_3006_QUYKHAC" NUMBER,

		"KLTH_CAP_DEN_3112_SONGAYTHANG" VARCHAR2(20 BYTE),
		"KLTH_CAP_DEN_3112_NSTT" NUMBER,
		"KLTH_CAP_DEN_3112_DTOAN_CHI_TX" NUMBER,
		"KLTH_CAP_DEN_3112_QUYKHAC" NUMBER,
		
		"NCAU_VON_N1" NUMBER,
		"NCAU_VON_N2" NUMBER,
		"NCAU_VON_N3" NUMBER,
		"GHICHU" VARCHAR2(20 BYTE),

		CONSTRAINT "QLNV_KHVONPHI_TC_NCAU_KHOACH_DTXD_GD3N_PK" PRIMARY KEY ("ID"));



---2

	CREATE TABLE "QLNV_KHVONPHI_TC_THOP_DTOAN_CHI_TX_HNAM" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"MA_DVI" VARCHAR2(20 BYTE),
		"TONG_CONG" NUMBER,
		"K331_TCONG" NUMBER,
		"K331_KHONG_TCHU_CO_DMUC_CONG" NUMBER,
		"K331_KHONG_TCHU_CO_DMUC_NX" NUMBER,
		"K331_KHONG_TCHU_CO_DMUC_VTCT" NUMBER,
		"K331_KHONG_TCHU_CO_DMUC_BQUAN" NUMBER,
		"K331_KHONG_TCHU_CHUA_DMUC_CONG" NUMBER,
		"K331_KHONG_TCHU_CHUA_DMUC_CNTT" NUMBER,
		"K331_KHONG_TCHU_CHUA_DMUC_THUE_KHO" NUMBER,
		"K331_KHONG_TCHU_CHUA_DMUC_MSAM_TSAN" NUMBER,
		"K331_KHONG_TCHU_CHUA_DMUC_BHIEM_HHOA" NUMBER,
		"K331_KHONG_TCHU_CHUA_DMUC_PHONG_CHONG_MOI_KPLB" NUMBER,
		"K331_KHONG_TCHU_CHUA_DMUC_VCHUYEN_BQUAN_TSAN_QHIEM" NUMBER,
		"K331_KHONG_TCHU_CHUA_DMUC_SCHUA_KHO_TANG" NUMBER,
		"K341_TCONG" NUMBER,
		"K341_LUONG" NUMBER,
		"K341_TX_THEO_DMUC" NUMBER,
		"K341_CHI_TX_KHONG_DMUC" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_TC_THOP_DTOAN_CHI_TX_HNAM_PK" PRIMARY KEY ("ID"));

---3
	CREATE TABLE "QLNV_KHVONPHI_TC_DTOAN_PHI_NXUAT_DTQG_THOC_GAO_HNAM" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"MA_CUC_DTNN_KVUC" VARCHAR2(20 BYTE),

		"NXUAT_THOC_LUONG_XUAT" NUMBER,
		"NXUAT_THOC_LUONG_NHAP" NUMBER,
		"NXUAT_THOC_LUONG_DMUC_PHI_XUAT" NUMBER,
		"NXUAT_THOC_LUONG_DMUC_PHI_NHAP" NUMBER,
		"NXUAT_THOC_LUONG_TTIEN" NUMBER,

		"NXUAT_GAO_LUONG_XUAT" NUMBER,
		"NXUAT_GAO_LUONG_NHAP" NUMBER,
		"NXUAT_GAO_LUONG_DMUC_PHI_XUAT" NUMBER,
		"NXUAT_GAO_LUONG_DMUC_PHI_NHAP" NUMBER,
		"NXUAT_GAO_LUONG_TTIEN" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_TC_DTOAN_PHI_NXUAT_DTQG_THOC_GAO_HNAM_PK" PRIMARY KEY ("ID"));


	CREATE TABLE "QLNV_KHVONPHI_TC_DTOAN_PHI_NXUAT_DTQG_VTU_TBI_GAO_HNAM" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"MA_VTU_TBI" VARCHAR2(20 BYTE),
		"SL" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_TC_DTOAN_PHI_NXUAT_DTQG_VTU_TBI_GAO_HNAM_PK" PRIMARY KEY ("ID"));

---4???
  CREATE TABLE "QLNV_KHVONPHI_TC_KHOACH_BQUAN_HNAM" 
   (	"ID" NUMBER(19,0), 
	"QLNV_KHVONPHI_ID" NUMBER(19,0), 
	"STT" VARCHAR2(20 BYTE), 
	"MA_CUC_DTNN_KVUC" VARCHAR2(20 BYTE), 
	"KPHI_BQUAN_CO_DMUC_THOC_TX" NUMBER, 
	"KPHI_BQUAN_CO_DMUC_THOC_LD" NUMBER, 
	"KPHI_BQUAN_CO_DMUC_GAO_TX" NUMBER, 
	"KPHI_BQUAN_CO_DMUC_GAO_LD" NUMBER, 
	"KPHI_BQUAN_CO_DMUC_TONG" NUMBER, 
	"KPHI_BQUAN_CHUA_DMUC_TONG" NUMBER, 
		"TONG_CONG" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_TC_KHOACH_BQUAN_HNAM_PK" PRIMARY KEY ("ID"));


	CREATE TABLE "QLNV_KHVONPHI_TC_KHOACH_BQUAN_TBI_VTU_HNAM" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"MA_VTU_TBI" NUMBER,
		"KPHI" NUMBER,
		"LOAI_DINH_MUC" VARCHAR2(20 BYTE), ---1 là có định mức, 0 là không định mức
		CONSTRAINT "QLNV_KHVONPHI_TC_KHOACH_BQUAN_TBI_VTU_HNAM_PK" PRIMARY KEY ("ID"));

---5

	CREATE TABLE "QLNV_KHVONPHI_TC_DTOAN_PHI_XUAT_DTQG_VTRO_CTRO_HNAM" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"MA_CUC_DTNN_KVUC" VARCHAR2(20 BYTE),
		"LUONG" NUMBER,
		"CPHI_XUAT_CO_DMUC" NUMBER,
		"CPHI_XUAT_CHUA_DMUC" NUMBER,
		"THANH_TIEN_CO_DMUC" NUMBER,
		"THANH_TIEN_KHONG_DMUC" NUMBER,
		"THANH_TIEN_CONG" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_TC_DTOAN_PHI_XUAT_DTQG_VTRO_CTRO_HNAM_PK" PRIMARY KEY ("ID"));


---6

	CREATE TABLE "QLNV_KHVONPHI_TC_KHOACH_DTOAN_CTAO_SCHUA_HTHONG_KHO_TANG_GD3N" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"TEN_CTRINH" VARCHAR2(20 BYTE),
		"NGUON_VON" VARCHAR2(20 BYTE),
		"LOAI_CT" VARCHAR2(20 BYTE),

		"TGIAN_KC" NUMBER,
		"TGIAN_HT" NUMBER,
		"DTOAN_DUOC_DUYET_CQUAN_QD" VARCHAR2(20 BYTE),
		"DTOAN_DUOC_DUYET_TONG_GTRI" NUMBER,
		"THIEN_KLUONG_N_DTOAN_KPHI_DEN_3006N" NUMBER,
		"THIEN_KLUONG_N_UOC_THIEN_CA_NAM_N" NUMBER,

		"TTOAN_KLUONG_N_DA_TTOAN_DEN_3006N" NUMBER,
		"TTOAN_KLUONG_N_UOC_THIEN_CA_NAM_N" NUMBER,

		"TONG_SO_N1" NUMBER,
		"TTOAN_NAM_TRUOC_CHUYEN_SANG_N1" NUMBER,
		"PSINH_MOI_N1" NUMBER,

		"TONG_SO_N2" NUMBER,
		"TTOAN_NAM_TRUOC_CHUYEN_SANG_N2" NUMBER,
		"PSINH_MOI_N2" NUMBER,

		"TONG_SO_N3" NUMBER,
		"TTOAN_NAM_TRUOC_CHUYEN_SANG_N3" NUMBER,
		"PSINH_MOI_N3" NUMBER,
		
		CONSTRAINT "QLNV_KHVONPHI_TC_KHOACH_DTOAN_CTAO_SCHUA_HTHONG_KHO_TANG_GD3N_PK" PRIMARY KEY ("ID"));


---7

	CREATE TABLE "QLNV_KHVONPHI_TC_KHOACHC_QUY_LUONG_N1" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"MA_CUC_DTNN_KVUC" VARCHAR2(20 BYTE),
		"BCHE_GIA0_N1" NUMBER,
		"DKIEN_CCVC_CO_MAT_0101N1" NUMBER,
		"DKIEN_HDONG_CO_MAT_0101N1" NUMBER,
		"BCHE_CHUA_SDUNG" NUMBER,
		"TONG_QUY_LUONG_PCAP_CKDG_THEO_LUONG_CCVC_HDLD" NUMBER,
		"TONG_SO" NUMBER,
		"CCVC_0101N1_CONG" NUMBER,
		"CCVC_0101N1_LUONG" NUMBER,
		"CCVC_0101N1_PCAP" NUMBER,
		"CCVC_0101N1_CKDG" NUMBER,
		"QUY_LUONG_TANG_THEM_DO_NANG_BAC_LUONG_CCVC_0101N1" NUMBER,
		"BCHE_CHUA_SDUNG_CONG" NUMBER,
		"BCHE_CHUA_SDUNG_LUONG_HE_SO234" NUMBER,
		"BCHE_CHUA_SDUNG_CKDG" NUMBER,
		"QUY_LUONG_PCAP_CKDG_THEO_LUONG_HDLD" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_TC_KHOACHC_QUY_LUONG_N1_PK" PRIMARY KEY ("ID"));


---8

	CREATE TABLE "QLNV_KHVONPHI_TC_DTOAN_CHI_DTQG_GD3N" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"MA_NDUNG_CHI" VARCHAR2(20 BYTE),
		"CHITIET" VARCHAR2(20 BYTE),
		"KHOACH_CHI_NSNN_N1" NUMBER,
		"KHOACH_CHI_NSNN_N2" NUMBER,
		"KHOACH_CHI_NSNN_N3" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_TC_DTOAN_CHI_DTQG_GD3N_PK" PRIMARY KEY ("ID"));


---9

	CREATE TABLE "QLNV_KHVONPHI_TC_TMINH_CHI_CAC_DTAI_DAN_NCKH_GD3N" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"TEN_DTAI_DAN_NCKH" VARCHAR2(20 BYTE),
		"MA_DVI" VARCHAR2(20 BYTE),
		"TGIAN_BDAU" NUMBER,
		"TGIAN_KTHUC" NUMBER,
		"KPHI_TONG_PHI_DUOC_DUYET" NUMBER,
		"KPHI_DA_DUOC_THIEN_DEN_TDIEM_BCAO" NUMBER,
		"KPHI_DKIEN_BTRI_N1" NUMBER,
		"KPHI_DKIEN_BTRI_N2" NUMBER,
		"KPHI_DKIEN_BTRI_N3" NUMBER,
		"KPHI_THU_HOI" NUMBER,
		"TGIAN_THU_HOI" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_TC_TMINH_CHI_CAC_DTAI_DAN_NCKH_GD3N_PK" PRIMARY KEY ("ID"));


---10

	CREATE TABLE "QLNV_KHVONPHI_TC_KHOACH_XDUNG_VBAN_QPHAM_PLUAT_DTQG_GD3N" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"TEN_VBAN" VARCHAR2(20 BYTE),
		"MA_HTHUC_VBAN" VARCHAR2(20 BYTE),
		"TGIAN_DKIEN" VARCHAR2(20 BYTE),
		"MA_DVI_CHU_TRI" VARCHAR2(20 BYTE),
		"DVI_PHOP" VARCHAR2(20 BYTE),
		"DTOAN_KPHI" NUMBER,
		"CCU_LAP_DTOAN" VARCHAR2(20 BYTE),
		CONSTRAINT "QLNV_KHVONPHI_TC_KHOACH_XDUNG_VBAN_QPHAM_PLUAT_DTQG_GD3N_PK" PRIMARY KEY ("ID"));


---11

	CREATE TABLE "QLNV_KHVONPHI_TC_DTOAN_CHI_UDUNG_CNTT_GD3N" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"NDUNG" VARCHAR2(20 BYTE),
		"MA_LOAI_KHOACH" VARCHAR2(20 BYTE),
		"MA_LOAI_DAN" VARCHAR2(20 BYTE),

		"TONG_DTOAN_SL" NUMBER,
		"TONG_DTOAN_GTRI" NUMBER,

		"THIEN_NAM_TRUOC" NUMBER,

		"DTOAN_THIEN_N_CB" NUMBER,
		"DTOAN_THIEN_N_TH" NUMBER,

		"DTOAN_THIEN_N1_CB" NUMBER,
		"DTOAN_THIEN_N1_TH" NUMBER,

		"DTOAN_THIEN_N2_CB" NUMBER,
		"DTOAN_THIEN_N2_TH" NUMBER,

		"DTOAN_THIEN_N3_CB" NUMBER,
		"DTOAN_THIEN_N3_TH" NUMBER,
		"GHI_CHU" VARCHAR2(20 BYTE),
		CONSTRAINT "QLNV_KHVONPHI_TC_DTOAN_CHI_UDUNG_CNTT_GD3N_PK" PRIMARY KEY ("ID"));


---12

	CREATE TABLE "QLNV_KHVONPHI_TC_DTOAN_CHI_MSAM_MMOC_TBI_CHUYEN_DUNG_GD3N" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"MA_VTU_TBI" VARCHAR2(20 BYTE),
		"TCONG_N1" NUMBER,
		"TCONG_N2" NUMBER,
		"TCONG_N3" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_TC_DTOAN_CHI_MSAM_MMOC_TBI_CHUYEN_DUNG_GD3N_PK" PRIMARY KEY ("ID"));


---13

	CREATE TABLE "QLNV_KHVONPHI_TC_THOP_NCAU_CHI_NSNN_GD3N" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"MA_NDUNG" VARCHAR2(20 BYTE),
		"MA_NHOM_CHI_NSNN" VARCHAR2(20 BYTE),

		"DTOAN_N" NUMBER,
		"UOC_THIEN_N" NUMBER,

		"TRAN_CHI_N1" NUMBER,
		"NCAU_CHI_N1" NUMBER,
		"CLECH_TRAN_CHI_VS_NCAU_CHI_N1" NUMBER,

		"SSANH_NCAU_N_VOI_N_1" NUMBER,

		"TRAN_CHI_N2" NUMBER,
		"NCAU_CHI_N2" NUMBER,
		"CLECH_TRAN_CHI_VS_NCAU_CHI_N2" NUMBER,

		"TRAN_CHI_N3" NUMBER,
		"NCAU_CHI_N3" NUMBER,
		"CLECH_TRAN_CHI_VS_NCAU_CHI_N3" NUMBER,

		CONSTRAINT "QLNV_KHVONPHI_TC_THOP_NCAU_CHI_NSNN_GD3N_PK" PRIMARY KEY ("ID"));


---14

	CREATE TABLE "QLNV_KHVONPHI_TC_THOP_NNCAU_CHI_TX_GD3N" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"MA_NDUNG" VARCHAR2(20 BYTE),
		"MA_NHOM_CHI" VARCHAR2(20 BYTE),

		"NAM_HHANH_N" NUMBER,

		"TRAN_CHI_N1" NUMBER,
		"NCAU_CHI_N1" NUMBER,
		"CLECH_TRAN_CHI_VS_NCAU_CHI_N1" NUMBER,

		"TRAN_CHI_N2" NUMBER,
		"NCAU_CHI_N2" NUMBER,
		"CLECH_TRAN_CHI_VS_NCAU_CHI_N2" NUMBER,

		"TRAN_CHI_N3" NUMBER,
		"NCAU_CHI_N3" NUMBER,
		"CLECH_TRAN_CHI_VS_NCAU_CHI_N3" NUMBER,

		CONSTRAINT "QLNV_KHVONPHI_TC_THOP_NNCAU_CHI_TX_GD3N_PK" PRIMARY KEY ("ID"));


---15

	CREATE TABLE "QLNV_KHVONPHI_TC_CTIET_NCAU_CHI_TX_GD3N" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"MA_NDUNG" VARCHAR2(20 BYTE),
		"MA_NHOM_CHI" VARCHAR2(20 BYTE),
		"THIEN_NAM_HHANH_N" VARCHAR2(20 BYTE),
		"NCAU_DTOAN_N1" NUMBER,
		"NCAU_DTOAN_N2" NUMBER,
		"NCAU_DTOAN_N3" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_TC_CTIET_NCAU_CHI_TX_GD3N_PK" PRIMARY KEY ("ID"));


---16

	CREATE TABLE "QLNV_KHVONPHI_TC_THOP_MTIEU_NVU_CYEU_NCAU_CHI_MOI_GD3N" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"MA_LVUC" VARCHAR2(20 BYTE),
		"MA_MUC_CHI" VARCHAR2(20 BYTE),
		"MTIEU_NVU" NUMBER,
		"CS_PHAP_LY_THIEN" NUMBER,
		"HDONG_CHU_YEU" NUMBER,
		"NGUON_KPHI" NUMBER,
		"TONG_SO" NUMBER,
		"CHI_CS" NUMBER,
		"CHI_MOI" NUMBER,

		"DTU_PTRIEN" NUMBER,
		"DTU_PTRIEN_CHI_CS" NUMBER,
		"DTU_PTRIEN_CHI_MOI" NUMBER,

		"CHI_TX" NUMBER,
		"CHI_TX_CHI_CS" NUMBER,
		"CHI_TX_CHI_MOI" NUMBER,
		CONSTRAINT "QLNV_KHVONPHI_TC_THOP_MTIEU_NVU_CYEU_NCAU_CHI_MOI_GD3N_PK" PRIMARY KEY ("ID"));














	CREATE TABLE "" 
	(
		"ID" NUMBER(19,0) NOT NULL ENABLE, 
		"QLNV_KHVONPHI_ID" NUMBER(19,0) NOT NULL ENABLE, 
		"STT" VARCHAR2(20 BYTE),
		"" VARCHAR2(20 BYTE),
		CONSTRAINT "" PRIMARY KEY ("ID"));

